### ISSUE TITLE
Uvoz podatkov

### ISSUE THREAD

**Issue by 1312Bravo** [jaanos/APPR-2018-19#2]
Poskušal sem z uvozom tabel, ki niso bile tipa 'CSV' ampak sem moral pod 'ogled vira strani'. 
Žal nisem znal uvoziti, zato sem tabelo kopiral v 'excel' in jo uvozil prek njega, vendar brez posebnih funkcij, katerih primer je v datoteki 'uvoz'.
Je to v redu?
Če ni, bi mi lahko pomagali?

Link: 
- https://hoopshype.com/salaries/players/2017-2018/
- http://www.fiba.basketball/rankingmen#|tab=fiba_europe

Lp, Urh

**Comment by jaanos** [comment]
Najprej, tale issue ni šel na pravo mesto - če želiš kaj vprašati glede svojega projekta, odpri issue na svojem repozitoriju. Na tem repozitoriju lahko odpreš issue, če bi rad npr. opozoril na kakšno napako glede samega vzorca.

Če pogledaš prvo povezavo, lahko opaziš, da so podatki v tabeli (`<table>`) z atributom `class="hh-salaries-ranking-table hh-salaries-table-sortable responsive"`. Potem lako to uporabiš pri samem uvozu:
```R
link <- "https://hoopshype.com/salaries/players/2017-2018/"
stran <- html_session(link) %>% read_html()
place <- stran %>% html_nodes(xpath="//table[@class='hh-salaries-ranking-table hh-salaries-table-sortable responsive']") %>%
  .[[1]] %>% html_table()
```
Pri takem uvozu se glava tabele pojavi kot prva vrstica, tako da se je bo potrebno znebiti, stolpcem pa bo treba nastaviti imena. Prvi stolpec je samo zaporedna številka - to lahko izpelješ iz podatkov, tako da lahko tudi to izpustiš. Plače pa bo seveda potrebno pretvoriti v številke. Vse skupaj bi potem šlo nekako tako:
```R
place <- place[-1, -1]
colnames(place) <- c("igralec", "placa")
place <- place %>% mutate(placa=parse_number(placa,
                                             locale=locale(grouping_mark=",")))
```
Funkcija `mutate` iz knjižnice `dplyr` se uporabi za nadomeščanje stolpcev (lahko tudi dodajanje). Za samo pretvorbo v števila se uporabi funkcija `parse_number` iz knjižnice `readr`, ki iz niza potegne prvo zaporedje števil, pri čemer vejice (ki so določene kot ločila tisočic) ignorira. Tako se ignorira tudi začetni `$`.

Mimogrede, če boš uvažal podatke za več let, svetujem, da narediš funkcijo, ki kot argument sprejme letnico (za zgornjo povezavo npr. kar 2017), nato pa iz ustrezne povezave prebere tabelo in ji doda stolpec z letnico (lahko kar v `mutate` dodaš parameter `leto=letnica`, kjer ime parametra poda ime stolpca, vrednost pa je tvoja spremenljivka z letnico). Funkcija (npr. `uvozi.place`) naj potem vrne podatke samo za eno leto. Vse skupaj lahko potem spraviš v eno razpredelnico s pomočjo funkcije `bind_rows` iz knjižnice `dplyr`:
```R
place <- bind_rows(lapply(2010:2017, uvozi.place))
```

Pri drugi povezavi lahko delaš na podoben način - je pa na sami strani več tabel z istimi atributi, brskalnik pa prikaže le eno glede na izbrani zavihek. Tabela za Evropo je peta po vrsti (prva je za cel svet), tako da lahko to podaš pri izbiri tabele:
```R
link <- "http://www.fiba.basketball/rankingmen#%7Ctab=fiba_europe"
stran <- html_session(link) %>% read_html()
rank.europe <- stran %>% html_nodes(xpath="//table[@class='fiba_ranking_table columnhover default_style responsive']") %>%
  .[[5]] %>% html_table()
```
